import Foundation
import SwiftData

enum BatchStatus: String, Codable {
    case active
    case completed
}

@Model
final class Batch {
    // startedAt is sorted on by every @Query in the app; batchLabel is
    // searched/matched (LaporanView) and looked up by prefix (Batch.nextLabel).
    #Index<Batch>([\.startedAt], [\.batchLabel])

    var id: UUID
    var batchLabel: String
    var startedAt: Date
    var endedAt: Date?
    var statusRaw: String

    // Whoever was selected in the header's worker roster when this batch
    // was started — see DashboardHeaderView. Empty when nobody was set.
    var qcStaff: String = ""

    // The role that worker had at the time, per WorkerRole — stored
    // alongside qcStaff (not looked up live from the roster) so a batch's
    // detail page still shows the right role even if the roster changes
    // or that worker is later removed. Empty for batches created before
    // this field existed.
    var qcRole: String = ""

    // True for batches generated by DebugSeeder. Not encoded into
    // batchLabel (unlike the old "-DEMO" suffix) — demo batches use the
    // exact same label format as real ones now, on purpose, so they're
    // visually indistinguishable. This flag is what lets "Hapus Data
    // Contoh" still find and remove only demo batches.
    var isDemo: Bool = false

    @Relationship(deleteRule: .cascade, inverse: \FruitRecord.batch)
    var fruitRecords: [FruitRecord] = []

    @Relationship(deleteRule: .cascade, inverse: \RejectedEvent.batch)
    var rejectedEvents: [RejectedEvent] = []

    var status: BatchStatus {
        get { BatchStatus(rawValue: statusRaw) ?? .active }
        set { statusRaw = newValue.rawValue }
    }

    init(batchLabel: String, qcStaff: String = "", qcRole: String = "") {
        self.id = UUID()
        self.batchLabel = batchLabel
        self.startedAt = .now
        self.endedAt = nil
        self.statusRaw = BatchStatus.active.rawValue
        self.qcStaff = qcStaff
        self.qcRole = qcRole
    }

    // Aggregates are computed from fruitRecords, never stored — see
    // Data_Architecture.md § "Why aggregates are computed, not stored".
    // These are convenience accessors, not persisted fields.
    var totalCount: Int { fruitRecords.count }
    var totalWeightG: Double { fruitRecords.reduce(0) { $0 + $1.weightG } }

    // Single pass over fruitRecords instead of filtering the whole array
    // once per grade — callers that need more than one grade's numbers
    // (the summary table, topGrade, the weight-distribution chart) should
    // read from this rather than calling count(for:)/weight(for:) in a
    // loop, which would each re-scan the full array. With batches now
    // realistically running into the thousands of records (see
    // DebugSeeder), 5 separate O(n) scans per render was measurably slow.
    var gradeBreakdown: [FruitGrade: (count: Int, weightG: Double)] {
        var result: [FruitGrade: (count: Int, weightG: Double)] = [:]
        for record in fruitRecords {
            var entry = result[record.grade] ?? (count: 0, weightG: 0)
            entry.count += 1
            entry.weightG += record.weightG
            result[record.grade] = entry
        }
        return result
    }

    func count(for grade: FruitGrade) -> Int {
        gradeBreakdown[grade]?.count ?? 0
    }

    func weight(for grade: FruitGrade) -> Double {
        gradeBreakdown[grade]?.weightG ?? 0
    }

    // Most recently graded fruit in this batch — nil once it has zero records.
    var lastRecord: FruitRecord? {
        fruitRecords.max(by: { $0.fruitSeq < $1.fruitSeq })
    }

    // Highest-count grade in this batch — nil once it has zero records.
    var topGrade: FruitGrade? {
        guard let best = gradeBreakdown.max(by: { $0.value.count < $1.value.count }), best.value.count > 0 else { return nil }
        return best.key
    }

    // Sequential per-day label, e.g. "B2026-08-17-01", "-02", ... — shared
    // by ContentView.startBatch (real batches) and DebugSeeder (demo
    // batches) so both produce identically-formatted labels and never
    // collide with each other's sequence numbers for the same day.
    static func nextLabel(for date: Date, existingLabels: [String]) -> String {
        let datePrefix = "B\(date.formatted(.iso8601.year().month().day()))"
        let existingSequences = existingLabels.compactMap { label -> Int? in
            guard label.hasPrefix(datePrefix + "-") else { return nil }
            return Int(label.dropFirst(datePrefix.count + 1))
        }
        let nextSequence = (existingSequences.max() ?? 0) + 1
        return "\(datePrefix)-\(String(format: "%02d", nextSequence))"
    }
}
